import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getCategory, getProductByPath, productCategories, products } from '../../../data/catalogData';
import { CategoryPage, ProductPage } from '../../../components/CatalogPages';
import { InquiryForm } from '../../../components/InquiryForm';

const pages = {
  '': ['Производитель поясных сумок', 'Специализация на конструкции поясных сумок и сопровождении образцов.', <><p>Минимальный заказ начинается от 50 шт. Образец обычно изготавливается за 7-15 дней, серийное производство - за 15-30 дней после утверждения.</p><p>Мы обсуждаем цвет, стропу, бегунок молнии и размещение логотипа как части одного изделия.</p></>],
  about: ['История трех месяцев работы над образцами', 'Один первый заказ на 1 000 изделий помог определить наш подход к сопровождению дизайна.', <><p>Американский бренд уличной одежды для активного отдыха пришел с идеей поясной сумки. В течение трех месяцев мы дорабатывали образцы для одного конкретного проекта.</p><p>Это не обещание одинакового срока для каждого заказа. Это реальный случай, когда повторная доработка была необходима для результата.</p><p>Tianjin Nameer International Trade Co., Ltd. и Tianjin Junyi Premium Trading Co., Ltd. используют одну производственную команду и одну фабричную территорию в Байгоу.</p></>],
  factory: ['Производство поясных сумок', 'Показываем только подтвержденные производственные процессы.', <><p>Швейный цех площадью 3 000 кв. м объединяет 35 производственных сотрудников и 15 сотрудников отдела продаж и поддержки.</p><p>Опыт изготовления сумок - более 20 лет. Годовой объем производства - более 200 000 изделий.</p></>],
  'custom-logo': ['Логотип и элементы отделки', 'Доступны печать, вышивка, нашивки, тканые этикетки и другие подтвержденные методы.', <p>Перед заказом можно запросить бесплатный макет размещения логотипа.</p>],
  'full-print': ['Полная запечатка поясных сумок', 'Рисунок, расположение деталей и швы проверяются до изготовления образца.', <p>Анна подтвердит требования к исходному файлу после выбора конструкции сумки.</p>],
  'oem-odm': ['Процесс OEM и ODM', 'От технического задания до утвержденного образца.', <ol><li>Отправьте референс, размеры и количество.</li><li>Подтвердите материал, цвет и логотип.</li><li>Утвердите макет и предложение.</li><li>Получите образец через 7-15 дней.</li></ol>],
  faq: ['Частые вопросы', 'Конкретные сроки и минимальные объемы.', <><p><strong>MOQ:</strong> от 50 шт.; уровни 50/100/300/500/1 000/3 000+.</p><p><strong>Образец:</strong> обычно 7-15 дней.</p><p><strong>Серийное производство:</strong> обычно 15-30 дней.</p></>],
  contact: ['Отправить запрос', 'Анна Вэй проверит референс, количество и детали кастомизации.', <><div className="card"><p><strong>Email:</strong> <a href="mailto:annawei@nameerbag.com">annawei@nameerbag.com</a></p><p><strong>WhatsApp:</strong> <a href="https://wa.me/8615102249548">008615102249548</a></p><p><strong>WeChat:</strong> 15102249548</p></div><InquiryForm locale="ru" product="Проект поясной сумки на заказ" /></>],
  'privacy-policy': ['Политика конфиденциальности', 'Данные запроса используются только для ответа и подготовки предложения.', <p>Мы не публикуем имя покупателя, компанию или детали запроса без разрешения.</p>]
};

export function generateStaticParams(){return [...Object.keys(pages).map(key=>({slug:key?[key]:undefined})),...productCategories.map(category=>({slug:[category.slug]})),...products.map(product=>({slug:[product.categorySlug,product.slug]}))];}
export async function generateMetadata({params}){const {slug}=await params;const key=slug?.join('/')||'';const category=getCategory(key);const product=getProductByPath(key);if(category||product){const title=category?category.ruTitle:product.ruTitle;const description=category?category.ruDescription:product.ruIntro;const en=`https://www.customwaistbag.com/${key}`;const ru=`https://www.customwaistbag.com/ru/${key}`;return{title,description,alternates:{canonical:ru,languages:{en,ru,'x-default':en}},openGraph:{title,description,url:ru,images:product?[product.gallery[0]]:products.filter(item=>item.categorySlug===key).map(item=>item.gallery[0])}};}const page=pages[key];if(!page)return{};const ru=`https://www.customwaistbag.com/ru${key?`/${key}`:''}`;const en=`https://www.customwaistbag.com/${key}`.replace(/\/$/,'/');return{title:page[0],description:page[1],alternates:{canonical:ru,languages:{en,ru,'x-default':en}}};}
export default async function RuPage({params}){const {slug}=await params;const key=slug?.join('/')||'';const category=getCategory(key);if(category)return <CategoryPage category={category} locale="ru"/>;const product=getProductByPath(key);if(product)return <ProductPage product={product} locale="ru"/>;const page=pages[key];if(!page)notFound();return <><section className="page-hero"><div className="shell"><div className="eyebrow">Custom Waist Bag</div><h1>{page[0]}</h1><p className="lead">{page[1]}</p><Link className="button" href={key?`/${key}`:'/'}>English</Link></div></section><section className="section"><div className="shell rich">{page[2]}</div></section></>;}
