import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getCategory, getProductByPath, productCategories, products } from '../../../data/catalogData';
import { CategoryPage, ProductPage } from '../../../components/CatalogPages';
import { InquiryForm } from '../../../components/InquiryForm';
import { RuHomePage } from '../../../components/RuHomePage';

const media = 'https://images.customwaistbag.com/assets';

const pages = {
  '': ['Производитель поясных сумок', 'Специализация на конструкции поясных сумок и сопровождении образцов.', <><p>Минимальный заказ начинается от 50 шт. Образец обычно изготавливается за 7-15 дней, серийное производство - за 15-30 дней после утверждения.</p><p>Мы обсуждаем цвет, стропу, бегунок молнии и размещение логотипа как части одного изделия.</p></>],
  about: ['История трех месяцев работы над образцами', 'Один первый заказ на 1 000 изделий помог определить наш подход к сопровождению дизайна.', <><p>Американский бренд уличной одежды для активного отдыха пришел с идеей поясной сумки и первым заказом на 1 000 изделий. Количество было определено, но конструкцию еще предстояло согласовать. Цвет, стропа, пуллер молнии и размещение логотипа должны были работать как единое изделие.</p><p>Работа над образцами для этого проекта продолжалась три месяца. Это не обещание одинакового срока для каждого заказа и не негативная история. В тот раз тщательная повторная доработка была правильным вложением в результат.</p><p>Этот опыт определил специализацию сайта: конструкция поясных сумок и терпеливое сопровождение образцов для покупателей, которым нужен вовлеченный производственный партнер.</p><h2>Одна производственная команда, две торговые компании</h2><p>Tianjin Nameer International Trade Co., Ltd. и Tianjin Junyi Premium Trading Co., Ltd. используют одну производственную команду и одну фабричную территорию в Байгоу. Производственный опыт в 20+ лет относится к изготовлению сумок, а не к дате регистрации компаний.</p><p>Площадь швейного цеха составляет 3 000 м². В команде 35 производственных сотрудников и 15 специалистов по продажам и поддержке. Годовой объем — 200 000+ изделий, экспорт — в 10+ рынков.</p></>],
  factory: ['Производство поясных сумок без подмены этапов', 'Показываем только подтвержденные производственные процессы и не выдаем отсутствующие фотографии за другие этапы.', <div className="grid three"><div className="card media-card"><img src={`${media}/images/factory/production-line.webp`} alt="Производственная линия в швейном цехе" /><div className="copy"><h3>Производственная линия</h3><p>Подтвержденный вид цеха из утвержденного набора материалов CWB.</p></div></div><div className="card media-card"><video controls poster={`${media}/videos/posters/manufacturing-video-01-poster.jpg`}><source src={`${media}/videos/manufacturing-video-01.mp4`} /></video><div className="copy"><h3>Пошив малых деталей</h3><p>Оператор сшивает небольшую деталь сумки оливкового цвета.</p></div></div><div className="card media-card"><video controls poster={`${media}/videos/posters/production-video-01-poster.jpg`}><source src={`${media}/videos/production-video-01.mp4`} /></video><div className="copy"><h3>Обработка края</h3><p>Крупный план обработки края поясной сумки.</p></div></div></div>],
  'custom-logo': ['Логотип и элементы отделки', 'Выберите способ, который подходит макету, материалу и назначению изделия.', <><div className="grid three">{['Шелкография','Вышивка','Резиновая нашивка','Тканая этикетка','Частная торговая марка','Термотрансфер','Кожаная нашивка','Металлический шильд','Индивидуальный пуллер молнии','Окрашивание по Pantone'].map((item)=><div className="card" key={item}><h3>{item}</h3><p>Доступность проверяется при согласовании спецификации и образца.</p></div>)}</div><p><Link className="button" href="/ru/contact">Запросить бесплатный макет логотипа</Link></p></>],
  'full-print': ['Полная запечатка поясных сумок', 'Рисунок, расположение деталей и конструкция проверяются вместе до изготовления образца.', <><p>Работа начинается с формы сумки, печатного макета и расположения швов. После выбора конструкции Анна подтвердит требования к исходному файлу.</p><img src={`${media}/images/process/customization-process.webp`} alt="Общая схема разработки поясной сумки на заказ" /><p>Схема показана как общее описание процесса и не означает, что каждый этап представлен отдельной фотографией.</p></>],
  'oem-odm': ['Процесс изготовления образца OEM и ODM', 'Практический путь от референса до утвержденного образца поясной сумки.', <ol><li>Отправьте референс, размеры, назначение и планируемое количество.</li><li>Подтвердите материал, цвет, стропу, пуллер молнии и способ нанесения логотипа.</li><li>Проверьте бесплатный макет логотипа и предложение.</li><li>Получите индивидуальный образец через 7–15 дней после подтверждения деталей.</li><li>Утвердите образец и начните серийное производство сроком 15–30 дней.</li></ol>],
  faq: ['Частые вопросы о заказе поясных сумок', 'Конкретные ответы для закупки и планирования.', <div className="faq">{[['Можно ли начать с 50 шт.?','Да. Уровни MOQ начинаются от 50 шт.: 50/100/300/500/1 000/3 000+. Итоговый MOQ зависит от конструкции.'],['Сколько времени занимает образец?','Обычно 7–15 дней после подтверждения деталей.'],['Каков срок серийного производства?','Обычно 15–30 дней после утверждения.'],['Возвращается ли стоимость образца?','Для 1 000+ шт. стоимость возвращается; для 500–1 000 шт. условия можно обсудить.'],['Публикуете ли вы цены?','Нет. Каждый проект рассчитывается после подтверждения спецификации.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>],
  contact: ['Отправить запрос', 'Анна Вэй проверит референс, количество и детали кастомизации.', <><div className="card"><p><strong>Email:</strong> <a href="mailto:annawei@nameerbag.com">annawei@nameerbag.com</a></p><p><strong>WhatsApp:</strong> <a href="https://wa.me/8615102249548">008615102249548</a></p><p><strong>WeChat:</strong> 15102249548</p></div><InquiryForm locale="ru" product="Проект поясной сумки на заказ" /></>],
  'privacy-policy': ['Политика конфиденциальности', 'Как используются данные, отправленные в запросе.', <><p>Информация, отправленная по форме, email или WhatsApp, используется только для ответа, подготовки предложения и обсуждения производства.</p><p>Мы не публикуем имя покупателя, название компании или детали запроса без разрешения.</p></>]
};

export function generateStaticParams(){return [...Object.keys(pages).map(key=>({slug:key?[key]:undefined})),...productCategories.map(category=>({slug:[category.slug]})),...products.map(product=>({slug:[product.categorySlug,product.slug]}))];}
export async function generateMetadata({params}){const {slug}=await params;const key=slug?.join('/')||'';const category=getCategory(key);const product=getProductByPath(key);if(category||product){const title=category?category.ruTitle:product.ruTitle;const description=category?category.ruDescription:product.ruIntro;const en=`https://www.customwaistbag.com/${key}`;const ru=`https://www.customwaistbag.com/ru/${key}`;return{title,description,alternates:{canonical:ru,languages:{en,ru,'x-default':en}},openGraph:{title,description,url:ru,images:product?[product.gallery[0]]:products.filter(item=>item.categorySlug===key).map(item=>item.gallery[0])}};}const page=pages[key];if(!page)return{};const ru=`https://www.customwaistbag.com/ru${key?`/${key}`:''}`;const en=`https://www.customwaistbag.com/${key}`.replace(/\/$/,'/');return{title:page[0],description:page[1],alternates:{canonical:ru,languages:{en,ru,'x-default':en}}};}
export default async function RuPage({params}){const {slug}=await params;const key=slug?.join('/')||'';if(!key)return <RuHomePage/>;const category=getCategory(key);if(category)return <CategoryPage category={category} locale="ru"/>;const product=getProductByPath(key);if(product)return <ProductPage product={product} locale="ru"/>;const page=pages[key];if(!page)notFound();return <><section className="page-hero"><div className="shell"><div className="eyebrow">Custom Waist Bag</div><h1>{page[0]}</h1><p className="lead">{page[1]}</p></div></section><section className="section"><div className="shell rich">{page[2]}</div></section></>;}
